##
## EPITECH PROJECT, 2020
## make file
## File description:
## Makefile
##


NAME	=	 groundhog

$(NAME):	
			cp src/main.py $@
			chmod +x $@

all:	$(NAME)
	
clean:

fclean: clean
	rm -rf $(NAME)

re: fclean all